#!/usr/bin/env bash

set -e

function log() {
    echo -e "\e[1m[action/images$1]\e[0m $2"
}

for COLLECTION in /etc/pinacotron/collections/*; do
    log "/$(basename $COLLECTION)" "Processing"
    if [[ "$PINACOTRON_IMAGES_PURGE" == "1" ]]; then
        log "/$(basename $COLLECTION)" "Purging"
        rm -rf /var/local/pinacotron/images/$(basename $COLLECTION)
    fi
    if [ ! -d "/var/local/pinacotron/images/$(basename $COLLECTION)" ]; then
        log "/$(basename $COLLECTION)" "Downloading"
        googleimagesdownload $(cat $COLLECTION/parameters.txt) -kf $COLLECTION/keywords.txt -o "/var/local/pinacotron/images/$(basename $COLLECTION)"
    else
        log "/$(basename $COLLECTION)" "Cached, skipping"
    fi
    log "/$(basename $COLLECTION)" "Done"
done
