#!/usr/bin/env bash

set -e

function log() {
    echo -e "\e[1m[action/posters$1]\e[0m $2"
}


if [[ "$PINACOTRON_POSTERS_PURGE" == "1" ]]; then
    log "" "Purging"
    rm -rf /var/local/pinacotron/posters/*
fi

mkdir -p /var/local/pinacotron/posters
mkdir -p /var/local/pinacotron/posters/png
mkdir -p /var/local/pinacotron/posters/pdf

find /var/local/pinacotron/images -type f |while read file; do
    shortname=$(basename "$file")
    WORDS=$(shuf -n1 /etc/pinacotron/words/${PINACOTRON_POSTERS_WORDS})
    log "/${shortname}" "Adding words to image - words='${WORDS}', convert_parameters=${PINACOTRON_POSTERS_CONVERT_PARAMETERS}"
    convert "$file" $(echo ${PINACOTRON_POSTERS_CONVERT_PARAMETERS} | xargs) "$(echo ${WORDS} | tr ' ' '\n')" /var/local/pinacotron/posters/$shortname
    log "/${shortname}" "Generating PNG"
    convert -density 300 -page A4 -resize 1500x2185\! /var/local/pinacotron/posters/$shortname /var/local/pinacotron/posters/png/$shortname.png
    log "/${shortname}" "Generating PDF"
    convert -density 300 -page A4 -resize 1500x2185\! /var/local/pinacotron/posters/$shortname /var/local/pinacotron/posters/pdf/$shortname.pdf
    rm /var/local/pinacotron/posters/$shortname
done

log "" "Generating PDF aggregate"
pdfunite /var/local/pinacotron/posters/pdf/*.pdf /var/local/pinacotron/posters.pdf
